Add no value validation
Picturepark/Picturepark.SDK.TypeScript pull request #370
Opened 2020-09-02 15:40 UTC by rjs-picturepark

2020-09-03 07:23 UTC, rjs-picturepark commented on src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/aggregation/aggregation.component.html
> +        <ng-container *ngIf="item.getDisplayName(locale) as displayName; else noValue">
Move no value validation to the get displayName functionality

2020-09-03 07:24 UTC, rjs-picturepark commented on src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/aggregation/aggregation.component.html
> +        <ng-container *ngIf="item.getDisplayName(locale) as displayName; else noValue">
Evaluate a way to not use the displayName in the view (maybe use a displayname getter in data contract)

2020-09-11 07:24 UTC, rjs-picturepark commented on src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/aggregation/aggregation.component.html
> +        <ng-container *ngIf="item.getDisplayName(locale) as displayName">
Use a pure pipe instead of the function call

2020-09-11 10:47 UTC, neotek requested changes

2020-09-11 10:47 UTC, neotek commented on src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/pipes/aggregation-item-translate.ts
> +@Pipe({ name: 'ppAggregationItemTranslate' })
make pipe pure.

2020-09-11 10:47 UTC, neotek commented on src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/aggregation/aggregation.component.html
> +          matTooltip="{{ item | ppAggregationItemTranslate }}"
Is it possible to execute the pipe only once? With *ngIf ?

2020-09-11 11:50 UTC, neotek approved these changes

2020-09-11 11:55 UTC, merged